export const allSuggestions = [
    { name: 'Aarav Kumar', email: 'aarav@example.com', photo: 'https://randomuser.me/api/portraits/men/1.jpg' },
    { name: 'Aisha Singh', email: 'aisha@example.com', photo: 'https://randomuser.me/api/portraits/women/2.jpg' },
    { name: 'Arjun Patel', email: 'arjun@example.com', photo: 'https://randomuser.me/api/portraits/men/3.jpg' },
    { name: 'Ishika Gupta', email: 'ishika@example.com', photo: 'https://randomuser.me/api/portraits/women/4.jpg' },
    { name: 'Kabir Sharma', email: 'kabir@example.com', photo: 'https://randomuser.me/api/portraits/men/5.jpg' },
    { name: 'Mira Kapoor', email: 'mira@example.com', photo: 'https://randomuser.me/api/portraits/women/6.jpg' },
    { name: 'Rohan Malhotra', email: 'rohan@example.com', photo: 'https://randomuser.me/api/portraits/men/7.jpg' },
    { name: 'Sanya Verma', email: 'sanya@example.com', photo: 'https://randomuser.me/api/portraits/women/8.jpg' },
    { name: 'Vikram Singh', email: 'vikram@example.com', photo: 'https://randomuser.me/api/portraits/men/9.jpg' },
    { name: 'Zara Khan', email: 'zara@example.com', photo: 'https://randomuser.me/api/portraits/women/10.jpg' },
    { name: 'Sara Verma', email: 'sara@example.com', photo: 'https://randomuser.me/api/portraits/women/11.jpg' },
    { name: 'Aryan Sharma', email: 'aryan@example.com', photo: 'https://randomuser.me/api/portraits/men/12.jpg' },
    { name: 'Zoya Khan', email: 'zoya@example.com', photo: 'https://randomuser.me/api/portraits/women/13.jpg' },
    { name: 'Rahul Kapoor', email: 'rahul@example.com', photo: 'https://randomuser.me/api/portraits/men/14.jpg' },
    { name: 'Isha Patel', email: 'isha@example.com', photo: 'https://randomuser.me/api/portraits/women/15.jpg' },
    { name: 'Raj Malhotra', email: 'raj@example.com', photo: 'https://randomuser.me/api/portraits/men/16.jpg' },
    { name: 'Ananya Singh', email: 'ananya@example.com', photo: 'https://randomuser.me/api/portraits/women/17.jpg' },
    { name: 'Karan Verma', email: 'karan@example.com', photo: 'https://randomuser.me/api/portraits/men/18.jpg' },
    { name: 'Neha Kumar', email: 'neha@example.com', photo: 'https://randomuser.me/api/portraits/women/19.jpg' },
    { name: 'Vishal Sharma', email: 'vishal@example.com', photo: 'https://randomuser.me/api/portraits/men/20.jpg' },
  ];